# Generated by Django 3.2.4 on 2021-07-22 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publics', '0002_remove_user_admin'),
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
