version: '3'

services:
  db:
    image: mysql
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=apartment
      - MYSQL_ROOT_PASSWORD=dmgkgk12
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - TZ=Asia/Seoul
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
    ports: 
      - 3306:3306
    platform: linux/x86_64

  django:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always  
    volumes:
      - .:/usr/src/app
    command: >-
        sh -c 'python manage.py migrate &&
               python manage.py runserver 0:8000'      

    environment:
      - DJANGO_DB_HOST=db
      - DJANGO_DB_NAME=apartment  
      - DJANGO_DB_PASSWORD=dmgkgk12
      - DJANGO_DB_USER=root  
      - DJANGO_DB_PORT=3306  
     
    depends_on:
      - db
    ports:
      - 8000:8000