# Generated by Django 3.2.4 on 2021-07-19 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.CharField(max_length=4, null=True)),
                ('password', models.CharField(max_length=4, null=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='admins.admin')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
