# Generated by Django 3.2.4 on 2021-07-22 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publics', '0002_remove_user_admin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User_APT',
        ),
    ]
